app: MyApp.app

devices:
  My iDevice:
    UDID  : lolffb28d74a6fraj2156090784avasc50725dd0
    screen: ipad_ios5

  Default Device:
    screen : low_ios5
    default: true
    UDID: <%= "something" + "_from_erb" %>

